title: Shruti Pandit
logo: /assets/img/passport.jpeg.jpg
description: <a href="http://https://github.com/shrutipandit707" align="center">Github </a> | <a href="https://www.linkedin.com/in/shruti-pandit-7b946883/?originalSubdomain=in"> LinkedIn </a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
