title: Shruti Pandit
logo: /assets/img/passport.jpeg.jpg
description: Repository containing portfolio of data science projects completed by me for academic, self learning, and hobby purposes. Presented in the form of iPython Notebooks.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
