title: Shruti Pandit
logo: /assets/img/passport.jpeg.jpg
description: <a href="http://https://github.com/shrutipandit707"> Github </a> 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
