title: Shruti Pandit
logo: /assets/img/passport.jpeg.jpg
description: <a href="http://https://github.com/shrutipandit707">Github </a> | <a href="https://www.linkedin.com/in/shruti-pandit-7b946883/?originalSubdomain=in"> LinkedIn </a> | <a hef="https://twitter.com/ShrutiPandit707?t=B1e8p-5T5AsS4y59qaou2A&s=09"> Twitter </a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
